basePath: /v1/api
definitions:
  model.MatchSerializer:
    properties:
      country_left:
        type: string
      country_right:
        type: string
      create_at:
        type: string
      date:
        type: string
      delete_at:
        type: string
      group_name:
        type: string
      id:
        type: integer
      location:
        type: string
      match_number:
        type: integer
      score:
        type: string
      update_at:
        type: string
    type: object
host: 127.0.0.1:5000
info:
  contact:
    email: wuxiaoshen@shu.edu.cn
    name: API Support
  description: This is a server for FIFA-World-Cup-2018.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: FIFA-World-Cup-2018 API
  version: "1.0"
paths:
  /matches/:
    get:
      consumes:
      - application/json
      parameters:
      - description: matchID
        in: query
        name: matchID
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.MatchSerializer'
            type: object
      security:
      - Bearer: []
      summary: List Match
      tags:
      - Match
securityDefinitions:
  Bearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
